"""empty message

Revision ID: 3c981a55bee5
Revises: 7661748f7881
Create Date: 2024-03-20 17:19:06.529628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3c981a55bee5'
down_revision: Union[str, None] = '7661748f7881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('removed', sa.Boolean(), nullable=False))
    op.add_column('account', sa.Column('removed_at', sa.DateTime(), nullable=True))
    op.alter_column('account', 'passport',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'passport',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('account', 'removed_at')
    op.drop_column('account', 'removed')
    # ### end Alembic commands ###
