"""set middle_name maybe nullable

Revision ID: 916272da4472
Revises: 923488c68eb7
Create Date: 2024-03-19 16:01:05.591146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '916272da4472'
down_revision: Union[str, None] = '923488c68eb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('passport', 'middle_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('passport', 'middle_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
