"""Create passport model

Revision ID: 923488c68eb7
Revises: b8bee9837151
Create Date: 2024-03-18 17:13:46.318489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '923488c68eb7'
down_revision: Union[str, None] = 'b8bee9837151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passport',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('removed', sa.Boolean(), nullable=False),
    sa.Column('removed_at', sa.DateTime(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('middle_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sex', sa.Boolean(), nullable=False),
    sa.Column('series', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('subdiv_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('issuing_place', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('birth_day', sa.Date(), nullable=False),
    sa.Column('birth_place', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passport_id'), 'passport', ['id'], unique=True)
    op.create_foreign_key(None, 'account', 'passport', ['passport'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.drop_index(op.f('ix_passport_id'), table_name='passport')
    op.drop_table('passport')
    # ### end Alembic commands ###
