"""empty message

Revision ID: c2b20dd8f5c5
Revises: 916272da4472
Create Date: 2024-03-19 16:53:02.630529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2b20dd8f5c5'
down_revision: Union[str, None] = '916272da4472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auditrecord', 'removed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('passport', 'removed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('passport', 'removed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('auditrecord', 'removed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
