version: "3.10"

x-rabbit-env: &x-rabbit-env
  RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
  RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}

x-postgres-env: &x-postgres-env
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_NAME: ${POSTGRES_NAME}

x-minio-env: &x-minio-env
  MINIO_ROOT_USER: ${MINIO_USER}
  MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}

# Containers:
# Backend
# Data checker
# Nginx
# RabbitMQ bitnami/rabbitmq
# MinIO bitname/minio
# BRUGES:
#   Запуск событий по времени

services:
  backend:
    build: containers/backend
    environment:
      <<: [ *x-postgres-env, *x-minio-env, *x-rabbit-env ]

    command: uvicorn main:app --host=0.0.0.0 --port=8000
    volumes:
      - "./containers/backend/app:/application"

    ports:
      - "8000:8000"


networks:
  rabbit-network:
  minio-network:
  sql-network:
  logic-network:


volumes:
  rabbit-data:
  minio-data:
  postgres-data: